type Patient = {
  hospital_id: string;
  patient_name: string;
  gender: "Male" | "Female";
  phone_number: string;
  next_delivery_date: string;
  status: "completed" | "due & paid" | "due & unpaid" | "assigned"; // Updated status values based on your earlier description
  delivery_area: string;
  location: string; // Added location field
  delivery_address: string;
};

// data/patients.ts
const patients: Patient[] = [
  {
    hospital_id: "8IWATQGO",
    patient_name: "Danielle Lee",
    phone_number: "+234-803-655-7098",
    next_delivery_date: "2025-06-27",
    gender: "Female",
    delivery_area: "Victoria Island, Lagos",
    location: "VI, Lagos",
    delivery_address: "123 Victoria Island, Lagos, Nigeria",
    status: "completed",
  },
  {
    hospital_id: "W9P5YZOP",
    patient_name: "John Doe",
    phone_number: "+234-703-915-1234",
    next_delivery_date: "2025-07-01",
    gender: "Male",
    delivery_area: "Garki, Abuja",
    location: "Garki, Abuja",
    delivery_address: "456 Garki, Abuja, Nigeria",
    status: "due & paid",
  },
  {
    hospital_id: "JK8K3DLO",
    patient_name: "Chioma Okafor",
    phone_number: "+234-703-813-8456",
    next_delivery_date: "2025-08-15",
    gender: "Female",
    delivery_area: "Ogui Road, Enugu",
    location: "Enugu City, Enugu",
    delivery_address: "789 Ogui Road, Enugu, Nigeria",
    status: "due & unpaid",
  },
  {
    hospital_id: "V7H8QWL0",
    patient_name: "Adebayo Femi",
    phone_number: "+234-806-456-7890",
    next_delivery_date: "2025-09-22",
    gender: "Male",
    delivery_area: "Agbowo, Ibadan",
    location: "Ibadan City, Oyo",
    delivery_address: "12 Agbowo, Ibadan, Nigeria",
    status: "assigned",
  },
  {
    hospital_id: "C9Y3XSKD",
    patient_name: "Seyi Bello",
    phone_number: "+234-811-345-6789",
    next_delivery_date: "2025-10-05",
    gender: "Female",
    delivery_area: "Nassarawa, Kano",
    location: "Kano City, Kano",
    delivery_address: "23 Nassarawa, Kano, Nigeria",
    status: "completed",
  },
  {
    hospital_id: "S1J0F8WQ",
    patient_name: "Uche Eze",
    phone_number: "+234-810-876-1234",
    next_delivery_date: "2025-11-18",
    gender: "Male",
    delivery_area: "Trans-Amadi, Port Harcourt",
    location: "Port Harcourt, Rivers",
    delivery_address: "456 Trans-Amadi, Port Harcourt, Nigeria",
    status: "due & paid",
  },
  {
    hospital_id: "L8H2U9YN",
    patient_name: "Ngozi Okoro",
    phone_number: "+234-810-567-8901",
    next_delivery_date: "2025-12-01",
    gender: "Female",
    delivery_area: "IBB Way, Calabar",
    location: "Calabar, Cross River",
    delivery_address: "89 IBB Way, Calabar, Nigeria",
    status: "due & unpaid",
  },
  {
    hospital_id: "M4N7K3OH",
    patient_name: "Chijioke Ugwu",
    phone_number: "+234-803-654-3210",
    next_delivery_date: "2026-01-15",
    gender: "Male",
    delivery_area: "Sabon Gari, Kaduna",
    location: "Kaduna City, Kaduna",
    delivery_address: "12 Sabon Gari, Kaduna, Nigeria",
    status: "assigned",
  },
  {
    hospital_id: "N8S9V4WX",
    patient_name: "Bola Johnson",
    phone_number: "+234-701-234-5678",
    next_delivery_date: "2026-02-10",
    gender: "Female",
    delivery_area: "Lekki Phase 1, Lagos",
    location: "Lekki, Lagos",
    delivery_address: "98 Lekki Phase 1, Lagos, Nigeria",
    status: "completed",
  },
  {
    hospital_id: "P4J5B2TL",
    patient_name: "Tolu Alabi",
    phone_number: "+234-705-987-6543",
    next_delivery_date: "2026-03-20",
    gender: "Male",
    delivery_area: "Ijemo, Abeokuta",
    location: "Abeokuta, Ogun",
    delivery_address: "88 Ijemo, Abeokuta, Nigeria",
    status: "due & paid",
  },
  {
    hospital_id: "Q3O0K5NE",
    patient_name: "Micheal Obi",
    phone_number: "+234-701-987-1234",
    next_delivery_date: "2026-04-14",
    gender: "Male",
    delivery_area: "Alhaji Road, Ilorin",
    location: "Ilorin, Kwara",
    delivery_address: "112 Alhaji Road, Ilorin, Nigeria",
    status: "due & unpaid",
  },
  {
    hospital_id: "R7E1B3OM",
    patient_name: "Emeka Nwosu",
    phone_number: "+234-705-123-4567",
    next_delivery_date: "2026-05-01",
    gender: "Male",
    delivery_area: "Jos Road, Jos",
    location: "Jos, Plateau",
    delivery_address: "24 Jos Road, Jos, Nigeria",
    status: "assigned",
  },
  {
    hospital_id: "T2G8A6PZ",
    patient_name: "Sarah Peters",
    phone_number: "+234-704-543-7890",
    next_delivery_date: "2026-06-15",
    gender: "Female",
    delivery_area: "Husseini Street, Maiduguri",
    location: "Maiduguri, Borno",
    delivery_address: "56 Husseini Street, Maiduguri, Nigeria",
    status: "completed",
  },
  {
    hospital_id: "U5H0V7R9",
    patient_name: "Ayodele Yusuf",
    phone_number: "+234-806-876-5432",
    next_delivery_date: "2026-07-30",
    gender: "Male",
    delivery_area: "Gudu, Abuja",
    location: "Abuja City, Abuja",
    delivery_address: "32 Gudu, Abuja, Nigeria",
    status: "due & paid",
  },
  {
    hospital_id: "V9N2Z6K4",
    patient_name: "Temilade Ojo",
    phone_number: "+234-705-456-7891",
    next_delivery_date: "2026-08-05",
    gender: "Female",
    delivery_area: "Surulere, Lagos",
    location: "Surulere, Lagos",
    delivery_address: "98 Lekki Phase 1, Lagos, Nigeria",
    status: "due & unpaid",
  },
  {
    hospital_id: "W3J4N2F5",
    patient_name: "Chukwudi Okoro",
    phone_number: "+234-704-567-1234",
    next_delivery_date: "2026-09-21",
    gender: "Male",
    delivery_area: "Ajao Street, Enugu",
    location: "Enugu City, Enugu",
    delivery_address: "11 Ajao Street, Enugu, Nigeria",
    status: "assigned",
  },
  {
    hospital_id: "X0I5U6P7",
    patient_name: "Ifeoma Nwachukwu",
    phone_number: "+234-703-321-4567",
    next_delivery_date: "2026-10-13",
    gender: "Female",
    delivery_area: "Ada-George, Port Harcourt",
    location: "Port Harcourt, Rivers",
    delivery_address: "34 Ada-George, Port Harcourt, Nigeria",
    status: "completed",
  },
  {
    hospital_id: "Y2D0B5Q7",
    patient_name: "Franklin Adeyemi",
    phone_number: "+234-809-123-4567",
    next_delivery_date: "2026-11-19",
    gender: "Male",
    delivery_area: "Ado Bayero, Kano",
    location: "Kano City, Kano",
    delivery_address: "17 Ado Bayero, Kano, Nigeria",
    status: "due & paid",
  },
  {
    hospital_id: "Z8M9F0T5",
    patient_name: "Ngozi Emeka",
    phone_number: "+234-701-234-5671",
    next_delivery_date: "2026-12-30",
    gender: "Female",
    delivery_area: "Mokola Hill, Ibadan",
    location: "Ibadan, Oyo",
    delivery_address: "13 Mokola Hill, Ibadan, Nigeria",
    status: "due & unpaid",
  },
  {
    hospital_id: "A3P2W6X9",
    patient_name: "Victor Omololu",
    phone_number: "+234-804-567-8900",
    next_delivery_date: "2027-01-25",
    gender: "Male",
    delivery_area: "Surulere, Lagos",
    location: "Surulere, Lagos",
    delivery_address: "90 Surulere, Lagos, Nigeria",
    status: "assigned",
  },
  {
    hospital_id: "B7S9Y0P3",
    patient_name: "Juliet Adebayo",
    phone_number: "+234-803-768-2135",
    next_delivery_date: "2027-02-17",
    gender: "Female",
    delivery_area: "Wuse, Abuja",
    location: "Wuse, Abuja",
    delivery_address: "67 Wuse, Abuja, Nigeria",
    status: "completed",
  },
];

export default patients;
